image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/sudoku.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/sudoku/blob/main/LICENSE]
image:https://github.com/m-m-m/sudoku/actions/workflows/build.yml/badge.svg["Build Status",link="https://github.com/m-m-m/sudoku/actions/workflows/build.yml"]

= mmm-sudoku

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-sudoku.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-sudoku/javadoc.svg["sudoku JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-sudoku]

The module `io.github.mmm.sudoku` (artifactId `mmm-sudoku`) provides a flexible model and engine for Sudoku puzzles.
Instead of hard-coding specific types of Sudokus we designed the Sudoku to have any number of `Partitionings`.
Each `Partitioning` can divide the Sudoku board entirely or partially into any number of partitions.
Every Sudoku always has `Column` and `Row` as `Partitioning`. Most of them also have `Box` but a Jigsaw Sudoku (Squiggly Sudoku) has `Regions` that are typically non-rectangular. The latter even allows an irregular `Dimension` such as a 5x5 board.
Even Killer Sudoku (SumDoku) is possible with this model.

The great thing about this design is that implementations like solvers or generators as well as the UI presenting the game can stay generic and need little to no knowledge of the different kind of Sudokus (except for SumDokus that add a whole new concept to the game).

== Features

This library offers the following features:

* Powerful but easy model for Sudoku and its variants
* Support for all common kinds of Sudoku variants
* Ability to add and implement your own variant in minutes
* History with unlimited undo/redo
* Support and auto-generation for candidates (pencil marks)
* Automatic error detection
* Generation of hints and solutions
* Validation of the Sudoku
* Eventing to observe changes and other aspects

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-sudoku</artifactId>
  <version>${mmm.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.sudoku;
```

= mmm-sudoku-fx

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-sudoku-fx.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://javadoc.io/badge2/io.github.m-m-m/mmm-sudoku-fx/javadoc.svg["SudokuFx JavaDoc", link=https://javadoc.io/doc/io.github.m-m-m/mmm-sudoku-fx]

The module `io.github.mmm.sudoku.fx` (artifactId `mmm-sudoku-fx`) provides the JavaFx GUI for the sudoku game engine.

== Features

This library offers the following features:

* Configuration of the Sudoku puzzle (dimension, difficulty, type, etc.)
* Presentation of the Sudoku-Board.
* Set values and candidates (pencil marks)
* Unlimited undo/redo
* Show candidates, get hits, etc.
*

== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-sudoku-fx</artifactId>
  <version>${mmm.version}</version>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.sudoku.fx;
```

= Research

Sudokus are an interesting topic both from mathematics as well as from computer-science.
Implementing this project allowed me to apply my knowledge about maths, graph-theory, data-modelling, boolean algebra and bit-mapping, efficient algorithm design, and many other disciplines.
The following links helped me to learn more about the topic and could be interesting also for others interested in this topic.

* https://en.wikipedia.org/wiki/Mathematics_of_Sudoku[Mathematics of Sudoku] (Wikipedia)
* https://uol.de/f/2/dept/informatik/ag/parsys/grahl_killersudokus_150222.pdf[Masterarbeit: Analyse, Implementierung und Vergleich von Strategien zum Lösen, Generieren und Bewerten von Killer-Sudokus] (Uwe Grahl)
* https://ct.de/yabc[Sudokus bewerten per Python-Skript] (ct' Magazin, Heise Medien)
* https://www.baeldung.com/java-sudoku[Create a Sudoku Solver in Java] (Baeldung)
* https://www.sudokuwiki.org/[SudokuWiki]
* https://sudoku.coach/[sudoku.coach]
* https://en.wikipedia.org/wiki/Glossary_of_Sudoku[Glossary of Sudoku] (Wikipedia)
* https://www.kakuro-knacker.de/pdf/summen_kombinationen.pdf[Summen Kombinationen]

Other open-source Sudoku implementations:

* https://ct.de/yabc[Sudokus bewerten per Python-Skript] (ct' Magazin, Heise Medien)
* https://pyimagesearch.com/2020/08/10/opencv-sudoku-solver-and-ocr/[OpenCV Sudoku Solver and OCR]
* https://github.com/BenJeau/JavaFX-Sudoku[JavaFX-Sudoku] (BenJeau)
* https://github.com/ksokolovic/JSudoku[JSudoku] (ksokolovic)
* https://github.com/oscr/JSudoku[JSudoku] (oscr)
* 

Best Android Sudoku Apps:

* https://www.andoku.com/apps/andoku3/[Andoku3]
* https://play.google.com/store/apps/details?id=com.conceptispuzzles.sumsudoku&hl=de&pli=1[SumDoku]
